shared:
  apiUnderTest:
    # Being able to run all tests against the latest stable version of 
    # the api or against the current version your working allows for 
    # comparing against a base line (the latest stable version)
    # in order to avoid regression. 
    #
    # In most case, the dev environnement can be used as the base line. 
    # Running the latest stable version and the current version locally is a 
    # great option if possible in your context.
    # Another option, is to set up a dedicated for the latest stable version.
    apiBaseUrl: http://localhost:$port